figure(iteration + 41)
surf(x1_, x2_, reshape(KDE, size(x1_)), 'EdgeColor', 'none')
xlim([min(grid_theta) max(grid_theta)])
ylim([min(grid_phi) max(grid_phi)])

xlabel('Zenith angle [deg]')
ylabel('Azimuth angle [deg]')
xticks(0 : 30 : 180)
yticks(-90 : 30 : 90)
set(gca, 'PlotBoxAspectRatio', [1, 1, 0.5])